AllCops:
  Exclude:
    - "db/schema.rb"
    - "Gemfile"
    - "spec/**/*"
  UseCache: false
Metrics/AbcSize:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Style/Documentation:
  Exclude:
    - 'lib/**/*'
